### ISSUE TITLE
[BUG][2.10] customImportMaps test flaky with security

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-dashboards-functional-test#883]
PRs that skip tests when security enabled:
* https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/881
* https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/884#pullrequestreview-1636197424

### Requirements
* Fix for the documentsSpec.
* Fix for the opensearchMapLayer spec

Potentially related to this: https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/856

**Comment by junqiu-lei** [comment]
Thanks @kavilla, when the #856 is resolved, I can help verify the fix of this issue

**Comment by raintygao** [comment]
I see referenced PRs have been merged, could we close this issue as completed ?

**Comment by raintygao** [comment]
Hi @junqiu-lei , we need to fix or remove all flaky tests before 2.12 release, could your team take a look on this flaky test? As i found the related tests are skipped in this repo but not in `dashboard-maps` repo.

**Comment by junqiu-lei** [comment]
The flaky tests only happened when security enabled, there are some other front plugin also have similar issue, I assume https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/856 need to be resolved firstly and then unblock flaky tests in plugins. cc @kavilla

**Comment by raintygao** [comment]
Hi @kavilla , is there any new insight about https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/856 ?

**Comment by junqiu-lei** [comment]
I just have locally tested maps integration tests several times on 2.12 cluster with security enabled from docker-compose, I didn't see security related failures again, attached with videos. I think we can revert back run the tests when security enabled and close this issue for now. WDYT? @kavilla @raintygao

<details>
  <summary>docker-compose.yml</summary>
  
  ### docker-compose.yml
  ```yml
version: '3'
services:
  opensearch-node1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchstaging/opensearch:2.12.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1,opensearch-node2 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2 # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD} # Sets the demo admin user password when using demo configuration (for OpenSearch 2.12 and later)
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-node2:
    image: opensearchstaging/opensearch:2.12.0
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchstaging/opensearch-dashboards:2.12.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net:
  
  ```
</details>



<details>

<summary>videos</summary>

https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/90288540/f81788ac-34f5-4fc7-836e-bf4d9984f26b


https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/90288540/81030599-85e5-4c6e-9db9-c6a6edb55eae


https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/90288540/211c2f50-34f5-494c-91fc-35a1eea783c5


https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/90288540/a2d543f6-e0ac-4c0b-b9e4-f27983df50c5

</details>
